### ISSUE TITLE
0.4.13 failed to deploy to PyPI

### ISSUE THREAD

**Issue by rishi-kulkarni** [scikit-sparse/scikit-sparse#113]
https://github.com/scikit-sparse/scikit-sparse/actions/runs/8199518657/job/22424836940

Looks like there was some auth error.

**Comment by AaronDJohnson** [comment]
I'm working on it. Hopefully I can get this fixed in the next day or so.

**Comment by AaronDJohnson** [comment]
Okay. So a day turned into a week... I'm hoping it's working now. Can you check on your end?

**Comment by rishi-kulkarni** [comment]
Yep, glad to use this with Python 3.12. Thanks a bunch!
