### ISSUE TITLE
0.4.14 pypi release failed

### ISSUE THREAD

**Issue by brentyi** [scikit-sparse/scikit-sparse#124]
`0.4.14` contains some fixes that seem critical for my system, but isn't available on PyPI! Would it be possible to fix this?

Relevant:
https://github.com/scikit-sparse/scikit-sparse/actions/runs/9249867715
https://pypi.org/project/scikit-sparse/

**Comment by AaronDJohnson** [comment]
This issue should be resolved with v0.4.15. Can you confirm that things are working for you?
