### ISSUE TITLE
Multiplying cholesky factor with a vector

### ISSUE THREAD

**Issue by quantdaddy** [scikit-sparse/scikit-sparse#13]
I want to calculate L_x where L_L' = A. x and A are known and A is sparse. Is there a way to do that using this package?

Thank you

**Comment by zoj613** [comment]
@quantdaddy have you ever been able to find the solution to your question?

**Comment by jor-** [comment]
Yes, you can do something like:

```
import sksparse.cholmod as ch  
factor = ch.cholesky(A, ordering_method="natural")
L = factor.L
L_x = L @ x
```

**Comment by zoj613** [comment]
> Yes, you can do something like:
> 
> ```
> import sksparse.cholmod as ch  
> factor = ch.cholesky(A, ordering_method="natural")
> L = factor.L
> L_x = L @ x
> ```

really? I thought the factorization was LL' = PAP' ? Meaning the `L` is the factorization of `PAP'`, not A. I think OP wants the non-fill-reduced factor of just `A`.

**Comment by jor-** [comment]
This is why I used ``ordering_method="natural"``. This disables the permutation so that LL' = A.

**Comment by zoj613** [comment]
> This is why I used `ordering_method="natural"`. This disables the permutation so that LL' = A.

Is there a way to quckily obtain the cholesky factor of A without involving extra steps while still getting maximum speed?
I currently use this to obain a nearly singlular matrix's cholesky so I can use it to generate random normal samples like so:
```python
        factor = sparse_cholesky(cov, ordering_method='default')
        L = factor.L()
        chol = factor.apply_Pt(L)
        out = mean + chol * out
```

Any way where I can make this any faster or more compact?

**Comment by jor-** [comment]
Your and my way are not the same but which on is faster depends on the matrix that you want to decompose. By the way: Your calculated ``chol`` is not the Choleksy factor of ``cov``. Usually it is not even a triangular matrix.

**Comment by zoj613** [comment]
> Your and my way are not the same but which on is faster depends on the matrix that you want to decompose. By the way: Your calculated `chol` is not the Choleksy factor of `cov`. Usually it is not even a triangular matrix.

I thought because `LL' = PAP'` then P'LL'P = A'? which makes `P'L` the cholesky factor?I guess that was wrong of me. How do I get the actual factor without using the natural ordering which slows things down considerably for  me?

**Comment by jor-** [comment]
Yes, it is correct that ``P'LL'P = A``, but ``P'L`` is not the Cholesky factor of ``A``.

**Comment by zoj613** [comment]
> Yes, it is correct that `P'LL'P = A`, but `P'L` is not the Cholesky factor of `A`.

Okay, understood. I can see how `P'L` wont be necessarily a triangular matrix. Any suggestions to obtain the actual Cholesky factor of A without using natural ordering?

**Comment by jor-** [comment]
No.

**Comment by zoj613** [comment]
> No.

Although the `chol` isnt really a cholesky factor, the statement `out = mean + chol * out` is still correct due to the affine transformation property of the normal distribution, right?

**Comment by jor-** [comment]
Yes, if ``std_normal`` is standard normal distributed, ``mean + chol * std_normal`` has mean ``mean`` and covariance matrix ``chol * chol^T``.
