### ISSUE TITLE
Cannot build wheel on Mac M1

### ISSUE THREAD

**Issue by schenkch** [scikit-sparse/scikit-sparse#132]
I cannot build the wheel for scikit-sparse on a Mac M1. Can you help me out with this, please? This is the errror I get: "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
      #warning "Using deprecated NumPy API, disable it with " \
       ^
      In file included from sksparse/cholmod.c:1261:
      sksparse/cholmod_backward_compatible.h:1:10: fatal error: 'cholmod.h' file not found
      #include "cholmod.h"
               ^~~~~~~~~~~
      1 warning and 1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-sparse
Failed to build scikit-sparse
ERROR: Could not build wheels for scikit-sparse, which is required to install pyproject.toml-based projects

**Comment by cgcgcg** [comment]
Did you follow https://github.com/scikit-sparse/scikit-sparse/blob/master/README.md#with-pip and install suite-sparse?

**Comment by schenkch** [comment]
Thank you. I realized that it was because some of the dependencies were not installed. It works now.
