### ISSUE TITLE
Cholesky update of A

### ISSUE THREAD

**Issue by AlexGrig** [scikit-sparse/scikit-sparse#18]
Dear Authors,

Thanks for your work. Could you say how hard is it to add here the updating of Cholesky of A.
This is implemented but for AA' only.

-Alex.

**Comment by anntzer** [comment]
Does http://pythonhosted.org/scikit-sparse/cholmod.html#sksparse.cholmod.Factor.cholesky_inplace not work for you?

**Comment by AlexGrig** [comment]
Hi,
Well, I meant that I need the rank-1 update of the Cholesky factorization of A. It is possible to compute the Cholesky of A, but I also need a Cholesky of (A + gg') where g is a column vector.

Thanks,

**Comment by anntzer** [comment]
I guess `update_inplace` should work just as well for `A`?  (i.e. the docs should really say: "update whatever decomposition is already there, but for `M+CC'`".)
See implementation at https://github.com/scikit-sparse/scikit-sparse/blob/master/sksparse/cholmod.pyx#L429 and the cholmod docs for `cholmod_updown`.
No guarantees, you'll have to confirm this yourself (and open a PR for the docs if this is indeed the case :-))

**Comment by AlexGrig** [comment]
Hi, anntzer
I have checked that and it works. So, I created the pull-request which updates the documentation.

One not related question maybe you could comment on. If a am able to compute Cholesky factorization analytically myself, would it be possible to feed this to the 'cholmod' library (the original one) so that later use the library for system solving, determinant computation etc. This seems to be a non-stardad use case of the library but still...

Thanks,

**Comment by anntzer** [comment]
I have no idea whether that's possible, but the format of the `cholmod_factor_struct` C struct is given in the official docs (http://suitesparse.com) so I'll let you check by yourself whether you can (or whether there's a function to) fiddle with them...

**Comment by jor-** [comment]
Does something speak against closing this issue?
