### ISSUE TITLE
scikit-sparse installation does not work without Cython installed

### ISSUE THREAD

**Issue by jor-** [scikit-sparse/scikit-sparse#20]
I tried to install scikit-sparse with pip but it does not work if Cython is not installed.
```
pip3 install scikit-sparse
```
```
Collecting scikit-sparse
  Using cached scikit-sparse-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-x1ljg7ce/scikit-sparse/setup.py", line 26, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'
```
It would be nice if Cython would be automatically installed in this case (or at least the user would be informed that he/she should install Cython first).

**Comment by anntzer** [comment]
It should be possible to modify setup.py based on https://setuptools.readthedocs.io/en/latest/history.html#id111; a PR is welcome.

(On the other hand I think that the ImportError clearly indicates that installing Cython first is needed.)
