### ISSUE TITLE
Copying a Cholesky factor

### ISSUE THREAD

**Issue by hronellenfitsch** [scikit-sparse/scikit-sparse#30]
Is it possible to add functionality to copy a Cholesky factor?

I have the following use case:
Starting from a single matrix, I spawn many worker processes that each modify the Cholesky
decomposition in different ways. Now, I need to calculate the initial decomposition of the same
matrix N times, once for each worker process. I would rather be able to pre-calculate it once and then
simply copy the factor N times (N can be quite large, so this is a significant time factor for me).

**Comment by njsmith** [comment]
I don't remember whether it's easy to copy a cholmod object off the top of
my head. It seems like a reasonable feature to support if cholmod
cooperates :-)

But also: if you're using UNIX and worker processes, note that you don't
actually need this: if you precompute the initial decomposition in the
parent process before calling fork, the worker processes will automatically
get their own copy-on-write copies of it.

**Comment by hronellenfitsch** [comment]
Thanks for the quick reply!
I am currently using a worker pool approach so that there won't be a lot of forking going on in general, but it might be worth a try to see if the overhead due to forking is not much smaller than the one due to computing the same Cholesky decomposition over and over again.

Thanks!

**Comment by njsmith** [comment]
Note that in that case your original request probably won't solve your
problem either -- it sounds like what you need is a way to convert a
cholmod object to and from a bunch of bytes (serialize/deserialize).

**Comment by hronellenfitsch** [comment]
Looking at the source code I noticed that there is an undocumented method _clone in the Factor class that seems to be doing precisely what I want.

**Comment by jor-** [comment]
@hronellenfitsch: Your issue is solved and can be closed?

This issue shows that it might be useful to replace/rename the undocumented ``_clone`` method by an official documented ``copy`` method. I might be do this in the future. Or want someone else do that?

**Comment by hronellenfitsch** [comment]
@jor- Yes, the issue can be closed, thank you.
Having a documented copy() method would be ideal!

**Comment by jor-** [comment]
A official `copy` method for the `Factor` class is added with the release 0.4.2 (see PR #33).
