### ISSUE TITLE
seeking help

### ISSUE THREAD

**Issue by hantongeee** [scikit-sparse/scikit-sparse#31]
Could anyone tell me that where can I find the package CHOLMOD to be installed?

**Comment by anntzer** [comment]
All we know is at https://scikit-sparse.readthedocs.io/en/latest/overview.html#requirements.  If you find out how to make it work on some other system, feel free to let us know so that we can add it to the docs.

**Comment by jor-** [comment]
CHOLMOD, along with the rest of SuiteSparse, is available from www.suitesparse.com.

The link to CHOLMOD is broken in https://scikit-sparse.readthedocs.io/en/latest/overview.html#requirements.

**Comment by jor-** [comment]
I updated the link in the master brunch.
