### ISSUE TITLE
Cholesky decomposition of unpermuted matrix

### ISSUE THREAD

**Issue by treverhines** [scikit-sparse/scikit-sparse#34]
Is it possible to get the Cholesky decomposition of A rather than PAP^T? I am trying to fold this package into my project and it would be easiest if I could get a sparse representation of the same matrix returned by, for example, np.linalg.cholesky. Thank you!

**Comment by jor-** [comment]
Yes. You have to use `cholesky(A, ordering_method='natural')`.  Then the matrix is not permuted and P is the identity matrix.

**Comment by sheqi** [comment]
Hi, I still have the question to decompose A rather than PAP^T, and I use cholesky(A, ordering_method='natural'), and them factor.L() to try to find the factor of A=LL^T, which is L. However, it seems not to return the same results as np.linalg.cholesky. I just want to check what's the different of comments to use between A=LL^T and A=LDL^T?  Thanks so much for the kindly help !

**Comment by jor-** [comment]
Hi @sheqi, your approach is right. Do you have the current version (0.4.2) of `scikit-sparse`? The previous version has a bug where `ordering_method='natural'` is not always taken into account.

**Comment by njsmith** [comment]
@sheqi: note that most matrices have multiple LL' decompositions that are equally valid, so you wouldn't necessarily expect numpy and scikit.sparse to return the exact same answer even if both are working correctly. If you want to know whether you have a correct LL' decomposition, you should compute the product LL' and see if it matches your original matrix.

**Comment by sheqi** [comment]
Hi, @jor-  after I install the new version, the bug has been fixed and has the same LL^T decomposition as I mention. Very helpful to have more information for ordering method to get the components. I recommend to add some issue on documentation about it. @njsmith Sure, the methods are quite good now, thanks for your kindly response. This package has really good computation advantage over normal python package !! Thanks all.

**Comment by treverhines** [comment]
I am able to get the Cholesky decomposition of A itself after installing version 0.4.2 and using `cholesky(A,order_method='natural').L()`. Thanks.

**Comment by jor-** [comment]
I am glad, that it now works.

@sheqi: You can find more informations about the ordering methods in the `CHOLMOD` documentation. But we will also add some more informations about this in the next release.
