### ISSUE TITLE
Bug after update

### ISSUE THREAD

**Issue by ChristopherMarkStrickland** [scikit-sparse/scikit-sparse#35]
Hi,

This bug only affects one of my computers, but it now occurs with a co-author  of mine after they updated their version of anaconda. 

I am using Ubuntu 14.04 (on both the computer that shows this issue, and two others that don't)
My colleague uses OSX.

A simple example of code that produces the bug is as follows:

`
import numpy as np
from cholmod import cholesky
from scipy.sparse import csc_matrix

np.set_printoptions(precision = 3)

#Construct sparse matrix
A = np.eye(5) * 3
A[:, 4] = 1.
A[4, :] = 1.
A[4, 4] = 3

#Compressed sparse column format
spA = csc_matrix(A)

#Compute cholesky decomposition
factor = cholesky(spA)

#Solve equation
x = np.ones(spA.shape[0])
print factor(x)
`
The output from the code is as follows:
python sparsechol.py 
/usr/lib/python2.7/dist-packages/scipy/sparse/coo.py:182: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(M) != 2:
/usr/lib/python2.7/dist-packages/scipy/sparse/coo.py:200: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.row) != 1 or np.rank(self.col) != 1:
/usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py:130: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.indices) != 1 or np.rank(self.indptr) != 1:
Traceback (most recent call last):
  File "sparsechol.py", line 18, in <module>
    print factor(x)
  File "cholmod.pyx", line 692, in cholmod.Factor.__call__ (Src/cholmod.c:7367)
  File "cholmod.pyx", line 688, in cholmod.Factor.solve_A (Src/cholmod.c:7248)
  File "cholmod.pyx", line 751, in cholmod.Factor._solve (Src/cholmod.c:8452)
  File "cholmod.pyx", line 769, in cholmod.Factor._solve_dense (Src/cholmod.c:8833)
  File "cholmod.pyx", line 292, in cholmod._error_handler (Src/cholmod.c:2925)
cholmod.CholmodError: ../Cholesky/cholmod_solve.c:1082: dimensions of L and B do not match (code -4)

Any help in resolving this issue would be greatly appreciated.

Chris.

**Comment by ChristopherMarkStrickland** [comment]
Hi,

Just some additional information. Note for comparison, on one of my other computers  (also running Ubuntu 14.04) I get

python testsp.py 
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
[ 0.4  0.4  0.4  0.4 -0.2]

I have no idea which update is causing this issue, which obviously isn't very helpful. Let me know if there is any output I could produce to aid in finding this bug.

Thanks,
Chris.

**Comment by ChristopherMarkStrickland** [comment]
Just some additional information, my colleague said the bug started after updating to Anaconda 4.4 on both Redhat and OSX.

**Comment by jor-** [comment]
Hi, can you please tell us which version of the following programs are you using when the bug occurs?

- operating system
- python
- numpy
- scipy
- suitesparse
- scikit-sparse

**Comment by jor-** [comment]
Your code (slightly modified) works for me with Python 3.6 and up to date packages.
 
```import numpy as np
from sksparse.cholmod import cholesky
from scipy.sparse import csc_matrix

np.set_printoptions(precision = 3)

#Construct sparse matrix
A = np.eye(5) * 3
A[:, 4] = 1.
A[4, :] = 1.
A[4, 4] = 3

#Compressed sparse column format
spA = csc_matrix(A)

#Compute cholesky decomposition
factor = cholesky(spA)

#Solve equation
x = np.ones(spA.shape[0])
print(factor(x))
```
The output is ``[ 0.4  0.4  0.4  0.4 -0.2]``.

**Comment by jor-** [comment]
The "error" in your second post is just a warning. You should not worry about this. Nevertheless it produces the correct result.

**Comment by ChristopherMarkStrickland** [comment]
The machine I am having trouble on is using:
Python 2.7.6
numpy 1.12.1
libsuitesparse-dev:amd64           1:4.2.1-3ubuntu1 
scipy 0.13.3
scikit.sparse 0.4.2 (also tried 0.4)
OS: Ubuntu 14.04
Note: It used to work, I am not sure what was updated, but it wasn't scikit.sparse when it broke. Looking below the only obvious change is numpy, but I am not sure how that could cause this issue.

Machine that works
Python 2.7.6
numpy 1.11.0
scipy 0.13.3
scikit.sparse (Some version with a 2009 ) copyright
OS Ubuntu 14.04
libsuitesparse-dev:amd64           1:4.2.1-3ubuntu1

I will try to get more details from my colleagues computer.

Note I wasn't worried about the warning issue in my second message, was just posting for comparison where it was working.

Thanks,
Chris.

**Comment by jor-** [comment]
Your suitesparse version (4.2.1)  is quite old (from 2013) maybe it does not work well with the newer scikit-sparse versions. I would recommend to try a newer suitesparse version which you can get from suitesparse.com.

**Comment by ChristopherMarkStrickland** [comment]
That version of suitesparse is the one that come packaged with Ubuntu 14.04.
I installed the latest stable version from source, which is version 4.5.5
I then rebuilt scikit.sparse with this, but I still get the same issue.

Note the sparse Cholesky decomposition works well, it is just the solve functions where I, and my colleague have this issue.

**Comment by jor-** [comment]
Okay. I also tested your code with Python 2.7. It also worked without an error. I used:
python                    2.7.13 
numpy                     1.12.1
scipy                     0.19.0
suitesparse               4.5.4
scikit-sparse             0.4.2 
My next suggestion would be to try a more up-to-date version of SciPy.
