### ISSUE TITLE
Implementation of solve_L() or solve_Lt() with LL' factorization (feature request)

### ISSUE THREAD

**Issue by mdevl** [scikit-sparse/scikit-sparse#38]
Hi guys,

In the documentation you stated:

_If you need an efficient implementation of solve_L() or solve_Lt() that works with the LL′LL′ factorization, then drop us a line, it’d be easy to add._

This would be the case for me. It is required if you want to use the Cholesky decomposition to sample from a multivariate Normal given the precision matrix (solve_Lt()). This is not an uncommon use case. In my case e.g., the precision matrix is pretty large and sparse. 

I think it would be quite valuable to have this in the future in scikit-sparse, especially if it's not associated with a lot of work. By the way, it also would be convenient to be able to evaluate L.dot(x) with A=LL' when working with covariance matrices (although this can be done manually without great loss of efficiency as well)

Thanks for all your work and for providing an open source wrapper for CHOLMOD

mdevl

**Comment by jor-** [comment]
Hi mdevl,
I released the version 0.4.3 which allows to use the `L` matrix of the `LL'` decomposition in `solve_L` and `solve_Lt`.
Best regards,
jor-

**Comment by mdevl** [comment]
Hello jor-,

that is exceedingly kind of you. Thank you very much. 

Best
mdevl
