### ISSUE TITLE
solve_A fails: on (n, 1) but not (n,2)

### ISSUE THREAD

**Issue by jsalvatier** [scikit-sparse/scikit-sparse#4]
With this setup:

```
import numpy as np 
from scikits.sparse import cholmod
from scipy.sparse import csc_matrix
n = 10 
m = csc_matrix(np.diag(np.ones(n)))
f = cholmod.cholesky(m)
```
This works fine:

```
shp = (n,2)
f(np.ones(shp))
```

But this does not 

```
shp = (n,1)
f(np.ones(shp))
```

Giving the error:
```CholmodError: ../Cholesky/cholmod_solve.c:979: dimensions of L and B do not match (code -4)```

I'm using this git repo and numpy 1.8.0.dev-7887c16. Scipy 0.11.0b1

**Comment by anntzer** [comment]
Seems solved as of now.  Please reopen if still an issue.
