### ISSUE TITLE
memory limitation for the use of factor = cholesky(Matrix)

### ISSUE THREAD

**Issue by feinstei** [scikit-sparse/scikit-sparse#40]
Hi,
I'm using the suite for a Chi-sq. problem which produce a large sparse matrix. 
It works fine with 7M (parameters) in a few min.
It dies (without comments) when passing to 49 M, after running ~ 10 h on my machine.
The memory is not a problem as I have 1.5 TB of RAM and I didn't see more than 16% of it used during run time.
The exact values are : 
dim(49024185, 49024185) 
number of non zero values = 1,237,581,215
My project deals with stars observed by a very large survey, so I would ultimately need to process ~ 500 M stars.
What is the limit of the scikit-sparse suite and do you have suggestions to overcome this problem ?
Regards,
Fabrice Feinstein

**Comment by jor-** [comment]
Hi,
when you use `scikit-sparse` for a problem which will have 2^31 or more non-zero values, as it is the case with your example, you should always use `use_long=True` at the function calls in `scikit-sparse` to get correct results. This allows you to have up to 2^61 non-zero entries which is the limit in `scikit-sparse` and would not even fit in your 1.5 TB of RAM.
Best reagrds,
jor-
