### ISSUE TITLE
Using GPU when calculating the Cholesky decomposition

### ISSUE THREAD

**Issue by rwolst** [scikit-sparse/scikit-sparse#42]
Is there a way to tell the Cholesky decomposition to use a GPU. I know its possible to do this in the CHOLMOD library.

**Comment by jor-** [comment]
Due to the CHOLMOD documentation this might be possible using
```
export CHOLMOD_USE_GPU=1
```
before using scikit-sparse and CHOLMOD.

**Comment by matthieuheitz** [comment]
I tried doing 
```
import os
os.environ["CHOLMOD_USE_GPU"] = "1"
import sksparse.cholmod
```
But it doesn't seem that my code uses the GPU...
