### ISSUE TITLE
solve_Lt() does not work right

### ISSUE THREAD

**Issue by melindalx** [scikit-sparse/scikit-sparse#43]
When I use the solve_Lt() to calculate L'x=b, I use the x returned to do L'x, and this does not equal to b, also when I use the dense matrix to do this calculation, the x I got from cholmod is different from the dense version. How can I get the right x?

**Comment by jor-** [comment]
You must use `solve_Lt(b, use_LDLt_decomposition=False)` and at least version 0.4.3 of `scikit-sparse`.

**Comment by melindalx** [comment]
After I put the parameter use_LDLt_decomposition, I got a result which is of the permutation of the original A, how can I get a result without permutating the original matrix? For example, how can I get a result same as what I get from dense version Cholesky decomposition?

**Comment by jor-** [comment]
The `ordering_method` parameter in the decompose functions allows you to disable permutation using the value `natural`. For example `cholesky(A, ordering_method="natural")`.

**Comment by melindalx** [comment]
Got it! It works! Thank you so much for your quick reply!
