### ISSUE TITLE
problem too large

### ISSUE THREAD

**Issue by melindalx** [scikit-sparse/scikit-sparse#44]
When I use cholesky function, it reports "sksparse.cholmod.CholmodTooLargeError: ../Supernodal/cholmod_super_symbolic.c:686: problem too large (code -3)", I use it like this:
factorQ = cholesky(Q, ordering_method="natural")
I also tried to add the use_long=True parameter, then it starts to eat up my memory and couldn't give a result.

**Comment by melindalx** [comment]
When I call the function without ordering_method parameter, it can run relatively fast, but I need the result of natural ordering.

**Comment by melindalx** [comment]
The matrix is 126007*126007 with 882037 non-zero elements.

**Comment by jor-** [comment]
It is like the message says: Your problem is to large for using `use_long=False`. Furthermore your memory is to small for solving your problem with `use_long=True`.

**Comment by melindalx** [comment]
Thank you for your reply! I'm wondering if there's any way to use solve_Lt with permutations and then transform the result to get the one corresponding to without permutations?

**Comment by jor-** [comment]
I think there is no easy way to calculate the Cholesky decomposition of a matrix directly from the Cholesky decomposition of its permuted version.
