### ISSUE TITLE
direct product with a matrix/vector

### ISSUE THREAD

**Issue by Evfro** [scikit-sparse/scikit-sparse#45]
Hi!

Is there any analog of `apply_P` method but for the factor itself? I mean, is there a method to compute a product `Lb` directly with a single method, rather than doing `factor.L().dot(b)` (`b` is given).

Thanks!

**Comment by jor-** [comment]
No, there is no analog method for computing a product with `L`.

`factor.L().dot(b)` it the way to go.

**Comment by Evfro** [comment]
Thanks for the answer! 
Is it something not even planned to be implemented? The problem with this approach is that it can be orders of magnitude slower than solving a triangular system. In my particular case I see the following timings:

`factor.apply_Pt(factor.L().dot(v))` : 323s

`factor.apply_Pt(factor.solve_Lt(y, use_LDLt_decomposition=False))`: 0.8s

**Comment by jor-** [comment]
No, it is not planned in short term.

The reason for this difference is that in the first line the matrix vector multiplication is done by SciPy and in the second line the calculation is done by suitesparse which is much faster.

**Comment by Evfro** [comment]
Actually, the most time is taken by `factor.L()` operation, not the `dot`.

I've created a simple wrapper around the `factor` object to cache the result of `.L()` operation and also implemented some convenience methods. Probably someone, who runs across the same problem, will find it useful.  Tested on Python 3.6, but should work on python 3.5 as well.

```python
class CholeskyFactor:
    def __init__(self, factor):
        self._factor = factor
        self._L = factor.L()
        self._transposed = False
        
    @property
    def T(self):
        self._transposed = True
        return self
    
    @property
    def transposed(self):
        current_state = self._transposed
        self._transposed = False
        return current_state
    
    def _dot(self, v):
        if self.transposed:
            return self._L.T.dot(self._factor.apply_P(v))
        else:
            return self._factor.apply_Pt(self._L.dot(v))
        
    def _factordot(self, factor):
        L = factor._factor.apply_Pt(factor._L)
        return self.dot(L.T if factor.transposed else L)
    
    def dot(self, v):
        is_factor = isinstance(v, self.__class__)
        return self._factordot(v) if is_factor else self._dot(v)
    
    def solve(self, y):
        x = self._factor
        if self.transposed:
            return x.apply_Pt(x.solve_Lt(y, use_LDLt_decomposition=False))
        else:
            return x.solve_L(x.apply_P(y), use_LDLt_decomposition=False)

    def update_inplace(self, A, beta):
        self._factor.cholesky_inplace(A, beta=beta)
        self._L = self._factor.L()
        
    def __matmul__(self, other):
        return self.dot(other)

    def __rmatmul__(self, other):
        return other.dot(self)
```

The usage is simple: `L_sparse = CholeskyFactor(cholesky(S))`, and then one can do things like `L_sparse.solve(y)` or `L_sparse.T.solve(y)` directly. It also supports `@` operator. The simplest case is to restore the original matrix `S`: `L_sparse @ L_sparse.T`
