### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by toddrme2178** [scikit-sparse/scikit-sparse#46]
I am trying to package scikit-sparse for openSUSE. However, there is no license file I can find, either in the github or tarball. In order for people to know how they can use your code it is really important to have a license file. Would it be possible to add one? Thank you.

**Comment by anntzer** [comment]
The license is at the end of the README.  In fact you can just use the README as license file...

**Comment by jor-** [comment]
I added a `LICENSE.txt` file.

**Comment by toddrme2178** [comment]
Thank you!
