### ISSUE TITLE
seg fault

### ISSUE THREAD

**Issue by marcinjurek** [scikit-sparse/scikit-sparse#47]
So I'm using your package and it often throws a segmentation fault. It seems a little random: sometimes the  same data will produce the error in one run and not in the other. However, for large matrices this happens pretty often. Not sure how to reproduce it. Any pointers?

**Comment by jor-** [comment]
Without a reproducible example of the segmentation fault it's gonna be hard to figure out the reason. It would be nice if you could figure out a reproducible example.

What operating system and what version of scikit-sparse, Python, Cython, NumPy and SciPy are you using?

**Comment by marcinjurek** [comment]
Alright, I think I figure out how to reproduce it!
So here is one of the matrices that are causing problems:
[A.tar.gz](https://github.com/scikit-sparse/scikit-sparse/files/2284545/A.tar.gz)

Here is the script that gives me the segmentation fault error:
```{python}
from sksparse.cholmod import cholesky_AAt
import scipy.sparse as sp

A = sp.load_npz('A.npz')
LambdaC = cholesky_AAt(A, beta=1.0, ordering_method='natural')
```
some other info:
OS: 
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.5.1804 (Core) 
Release:        7.5.1804

scikit-sparse: version 0.4.3
Python version 3.4.8
Scipy version 1.1
Cython 0.28.3
numpy version 1.14.4

Do you think you would be able to help? Thanks!

**Comment by marcinjurek** [comment]
In the meantime I also emailed prof. Davis, who suggested that using cholmod_l_ methods might help. To that end, I set the use_long flag to True. This didn't seem to help, unfortunately:

```{bash}
> /home/grad/marcin.jurek/multiresolution-filter/python/filters/Multiresolution.py(156)_correct()
-> LambdaC = cholesky_AAt(A, beta=1.0, ordering_method='natural', use_long=True)
(Pdb) A
<14458x5375 sparse matrix of type '<class 'numpy.float64'>'
        with 309078 stored elements in Compressed Sparse Column format>
(Pdb) n
/home/grad/marcin.jurek/multiresolution-filter/python/filters/Multiresolution.py:156: 
cholmodTypeConversionWarning: array contains 32 bit integers; but 64 bit integers are needed; 
slowing down due to converting
  LambdaC = cholesky_AAt(A, beta=1.0, ordering_method='natural', use_long=True)
Segmentation fault (core dumped)
```
Above, we see that the matrix I'm using has indeed 64-bit float elements (I added an extra line to ensure that's the case). However somehow, this doesn't seem to be recognized by the wrapper. And even though the flag is set to true (and so the cholmod_l_) method is being used, seg fault still occurs. I'll see if I can figure it out myself, and will document my progress here.

**Comment by marcinjurek** [comment]
Hey, any chance to have that looked at?

**Comment by jor-** [comment]
For me your example works without a segfault:
```
>>> from sksparse.cholmod import cholesky_AAt
>>> import scipy.sparse as sp
>>> A = sp.load_npz('A.npz')
>>> LambdaC = cholesky_AAt(A, beta=1.0, ordering_method='natural')
>>> LambdaC
<sksparse.cholmod.Factor object at 0x7f0ecb0337b8>
```
Maybe this is not a `scikit-sparse` issue. I use the following versions:
```
python                    3.7.0
cython                    0.28.5
numpy                     1.15.0 
scipy                     1.1.0
suitesparse               5.2.0
scikit-sparse             0.4.3
```
What `suitesparse` version are you using? If it is outdated, maybe it helps to update to a newer one.

**Comment by marcinjurek** [comment]
ok, thanks for checking. Other people also told me they were able to run it on their machines. So it seems like a version problem on my end.
