### ISSUE TITLE
Can be used for importing Harwell-Boeing or Rutherford-Boeing matrices?

### ISSUE THREAD

**Issue by e-dub** [scikit-sparse/scikit-sparse#48]
Can this software be used in concert with SuiteSparse to import Harwell-Boeing or Rutherford-Boeing matrices into Python?

**Comment by jor-** [comment]
You can load and write matrices in Harwell-Boeing format using `scipy` with `scipy.io.hb_read` and `scipy.io.hb_write`. After that you can decompose these matrices using `SuiteSparse`.

**Comment by e-dub** [comment]
Thank you for your response.  I am though looking for an alternative as `scipy.io.hb_read` only works with non-symmetric sparse matrices and mine our symmetric.

**Comment by jor-** [comment]
Yes, you are right. It is just implemented for general matrices in `scipy.io.hb_read`. For now `scikit-sparse` has not implemented save and load functions itself.

**Comment by e-dub** [comment]
I found a solution using BeBOP Sparse Matrix Converter to convert to MarketMatrix and then importing this into Python.
