### ISSUE TITLE
conda installation problem on a Mac

### ISSUE THREAD

**Issue by cgreenberg** [scikit-sparse/scikit-sparse#52]
I installed suitesparse and scikits.sparse via conda (python 2.7.15). Then when I try "from sksparse.cholmod import cholesky" I get this error:

```
ImportError: dlopen(/anaconda2/lib/python2.7/site-packages/sksparse/cholmod.so, 2): Library not loaded: @rpath/libcholmod.3.0.11.dylib
  Referenced from: /anaconda2/lib/python2.7/site-packages/sksparse/cholmod.so
  Reason: image not found
```

**Comment by jor-** [comment]
What version of scikit-sparse did you try to install? Do you have the same problem with other versions?

**Comment by cgreenberg** [comment]
Conda looks to try to install `scikit-sparse-0.4.4`. I tried this because the pip version of scikit-sparse didn't seem to be able to find homebrew's `suitesparse/cholmod.h`, I should make a different issue for that.

**Comment by jor-** [comment]
Do you have the same problem with other scikit-sparse versions, like for example 0.4.3? What version of suitesparse do you use?

**Comment by kalkairis** [comment]
I am using a linux machine and am also having trouble installing the latest version. 
It seems that pip install searches for `suitesparse/cholmod.h` and does not find it. 
The same issue occurs in version 0.4.3

**Comment by qianyiforma** [comment]
This solved my issue:
```
conda install -c conda-forge suitesparse
```

**Comment by zhanghongboinsa** [comment]
I have the same problem for package openturns in MacOs.

packages/openturns/_common.so, 2): Library not loaded: @rpath/libcholmod.3.0.11.dylib
 Referenced from: opt/anaconda3/lib/libceres.1.14.0.dylib
 Reason: image not found

 I solved it by removing the conda-forged version by: 

conda remove --force openturns
and then install with pip

pip install openturns,

after that it works well.
