### ISSUE TITLE
File permission mistake

### ISSUE THREAD

**Issue by eatradish** [scikit-sparse/scikit-sparse#54]
```
 ~/a/scikit-sparse-0.4.4  ll                                                                                                                     Fri May 24 08:20:21 2019
total 100K
-rw------- 1 sakiiily sakiiily 1.4K May 24  2018 LICENSE.txt
-rw------- 1 sakiiily sakiiily  202 Nov  6  2018 MANIFEST.in
-rw------- 1 sakiiily sakiiily 1.1K Nov  7  2018 PKG-INFO
-rw-r----- 1 sakiiily sakiiily 3.3K May  6  2017 README.md
drwx------ 2 sakiiily sakiiily 4.0K Nov  7  2018 doc/
drwx------ 2 sakiiily sakiiily 4.0K Nov  7  2018 scikit_sparse.egg-info/
-rw-r----- 1 sakiiily sakiiily  204 Nov  7  2018 setup.cfg
-rw-r----- 1 sakiiily sakiiily 3.1K May  6  2017 setup.py
drwx------ 3 sakiiily sakiiily 4.0K Nov  7  2018 sksparse/
-rw-r----- 1 sakiiily sakiiily  63K May  6  2017 versioneer.py
 ```
`PKG-INFO` and `scikit_sparse.egg-info/requires.txt` Caused pip to install any other module error.
example:
```
 !  ~/acbs   staging  pip3 install -r requirements.txt --user                                                                         242ms  Fri May 24 07:00:43 2019
....
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.7/site-packages/scikit_sparse-0.4.4-py3.7.egg-info/PKG-INFO'
```

**Comment by jor-** [comment]
What file permissions are you expecting? Permissions for the group and other as well?

Did you get this error as the user sakiiily or as another user? As the owner of the files you should not have any file permission problem.

**Comment by eatradish** [comment]
> What file permissions are you expecting? Permissions for the group and other as well?
> 
> Did you get this error as the user sakiiily or as another user? As the owner of the files you should not have any file permission problem.

This is the file structure in the current source tarball.
File should 644, and directory should 0755....

**Comment by jor-** [comment]
Thank you for pointing that out. We will take this into account in the next release.
