### ISSUE TITLE
Numerical inconsistency between scikit-sparse and numpy Cholesky's

### ISSUE THREAD

**Issue by MartijnOei** [scikit-sparse/scikit-sparse#56]
I'm writing code to generate samples from a multivariate normal distribution using the Cholesky of the corresponding covariance matrix.
However, the Cholesky's of my matrices, calculated using scikit-sparse, are incorrect, although simple checks show that the covariance matrices are both symmetric and positive-definite.

I've created a working example that generates such a covariance matrix, shows that it is symmetric and positive-definite, and then calculates the Cholesky using both scikit-sparse and numpy. The numpy version is correct; the scikit-sparse version unfortunately isn't.

```python
import numpy, sys
from scipy import sparse
from scipy.spatial.distance import pdist, squareform
from sksparse import cholmod
from matplotlib import pyplot

mapHeight              = 16
mapWidth               = 32
sigma                  = .1
thresholdSparsity      = 1e-8
numericalStabilisation = 1e-6


# Generate matrix.
mapXs, mapYs           = numpy.meshgrid(numpy.linspace(0, 2, num = mapWidth, endpoint = True), numpy.linspace(0, 1, num = mapHeight, endpoint = True))
distances              = squareform(pdist(numpy.stack((mapXs.flatten(), mapYs.flatten())).T))
# Calculate covariance matrix.
#A                      = numpy.square(numpy.maximum(1 - distances / sigma, 0)) # piece-wise polynomial kernel (which is sparse by design)
A                      = numpy.exp(-1 / 2 * numpy.square(distances / sigma)) # squared exponential kernel
# Sparsify covariance matrix.
A                      = A * (A > thresholdSparsity)
# Stabilise covariance matrix.
numpy.fill_diagonal(A, 1 + numericalStabilisation)


# Choose a simpler matrix:
#A                      = numpy.array([[4.0, 0.0], [0.0, 9.0]])
#A                      = numpy.array([[4.0, 0.0, 1.0], [0.0, 16.0, 0.0], [1.0, 0.0, 4.0]])


# Verify symmetry and positive-definiteness.
if (numpy.array_equal(A, A.T)):
    print("A is symmetric!")
else:
    print("A is not symmetric!")
    sys.exit()
if (numpy.all(numpy.linalg.eigvals(A) > 0)):
    print ("A is not only symmetric, but also positive-definite!")
else:
    print("A is symmetric, but not positive-definite!")
    sys.exit()


# Generate a sparse version of A.
A_CSC                  = sparse.csc_matrix(A)
factor                 = cholmod.cholesky(A_CSC)
cholesky1              = factor.L().toarray()[factor.P()[:, numpy.newaxis], factor.P()[numpy.newaxis, :]]
cholesky2              = numpy.linalg.cholesky(A)


print("original matrix:\n", A)
print("scikit cholesky:\n", cholesky1)
print("numpy cholesky:\n",  cholesky2)

print("maximum absolute difference:",             numpy.amax(numpy.abs(cholesky1 - cholesky2)))
print("scikit cholesky accuracy (0 is perfect):", numpy.amax(numpy.abs(numpy.dot(cholesky1, cholesky1.T) - A)))
print("numpy cholesky accuracy (0 is perfect):",  numpy.amax(numpy.abs(numpy.dot(cholesky2, cholesky2.T) - A)))

print("elements in matrix:", A.shape[0] * A.shape[1])
print("non-zero elements in sparse rep:", A_CSC.nnz)


pyplot.imshow(cholesky1)
pyplot.title("Cholesky (scikit)")
pyplot.show()
pyplot.imshow(cholesky2)
pyplot.title("Cholesky (numpy)")
pyplot.show()
```
I have included two other small matrices `A`, for which the Cholesky's _are_ the same. Activate one by removing the appropriate `#`. Curiously, the problem also persists if I use a kernel for the covariance matrix which makes it sparse by design.

Any ideas? Many thanks!
Martijn

**Comment by MartijnOei** [comment]
<img width="959" alt="Screenshot 2019-06-20 at 19 20 57" src="https://user-images.githubusercontent.com/25039233/59876115-fd969500-93a2-11e9-8378-7c8c06b00141.png">
Here's the inconsistency shown graphically.

**Comment by jor-** [comment]
The scikit-sparse calculations are correct as well but they are not the same as the calculations from NumPy because scikit-sparse uses permutations by default.
If you use 
```
factor = cholmod.cholesky(A_CSC)
```
then you get a Cholesky decomposition of a permuted version of `A_CSC`. You can not expect `cholesky1` be equal to `cholesky2`. `factor.L()` is the Cholesky factor of the permuted `A_CSC` and `numpy.linalg.cholesky(A)` the Cholesky factor of the unpermuted `A_CSC`. Your `cholesky1` is not the Cholesky factor of the unpermuted `A_CSC`. It is not even a lower triangle matrix. If you want the unpermuted Cholesky factor of `A_CSC` you have to use 
```
factor = cholmod.cholesky(A_CSC, ordering='natural')
cholesky1 = factor.L()
```
Then cholesky1 is (numerically) equal to cholesky2.

If you want to calculate the matrix represented by a permuted Cholesky decomposition you have to do it like this
```
p = factor.P()
p_inverse = np.empty_like(p)
p_inverse[p] = np.arange(len(p))
C = factor.L().toarray()[p_inverse[:, numpy.newaxis], p_inverse[numpy.newaxis, :]]
B = np.dot(C, C.T)
```
Here B (numerically) equals A.

**Comment by MartijnOei** [comment]
Dear Joscha,

Thank you for your swift and helpful reply! I have found that using `ordering_method="natural"` (rather than `ordering="natural"`) indeed does the job. That's great to see. :)
I wondered why I hadn't found this before (I experimented with many of the kwargs), but it appears due to the fact that I've been browsing an old version of the documentation. I learned about the existence of scikit-sparse via Google, and on there the first documentation link is https://pythonhosted.org/scikit-sparse/cholmod.html, in which the `ordering_method` kwarg doesn't exist yet. Maybe it's an idea to update that documentation to what is found on https://scikit-sparse.readthedocs.io/en/latest/, to avoid future confusion? If `ordering_method` had been in the documentation I'd been consulting, I'd surely have experimented with it.

Also (would be interesting to hear your viewpoint on this), I find it personally unintuitive (for an unexperienced adopter) that
```python
factor = cholmod.cholesky(A_CSC)
matrix = factor.L().toarray()
```
does _not_ result in ```matrix``` being the Cholesky _L_ of `A_CSC` (or `A`), at least in the explicit sense _L L^T = A_. I understand that this is because you use an intelligent optimisation under the hood - but I feel this is something that unexperienced users should not have to worry about, and that experienced users should be able to leverage if they want to. Therefore, I'd personally let `ordering_method="natural"` be the default.
Another (perhaps easier option) is to expand https://scikit-sparse.readthedocs.io/en/latest/cholmod.html#quickstart slightly, to provide a minimal example of how  to find what people (like me) would 'naively' consider to be the Cholesky of `A` or `A_CSC`, emphasising the `ordering_method` kwarg.

Finally, I'm still confused about the last part of your comment. If I understand correctly, you say you can either _not_ leverage the internal permutation functionality, and calculate the 'naive' Cholesky with `ordering_method="natural"`, _or_ leverage the permutations, but at the 'price' of adding a few not-directly-obvious lines of code.
However,
```python
factor       = cholmod.cholesky(A_CSC, ordering_method = "natural")
cholesky1    = factor.L().toarray()

factorSmart  = cholmod.cholesky(A_CSC)
p            = factorSmart.P()
p_inverse    = numpy.empty_like(p)
p_inverse[p] = numpy.arange(len(p))
C            = factorSmart.L().toarray()[p_inverse[:, numpy.newaxis], p_inverse[numpy.newaxis, :]]

print(numpy.amax(numpy.abs(cholesky1 - C)))
```
shows that `cholesky1` and `C` are not the same. However, you indicate that `B = numpy.dot(C, C.T)` indeed matches `A`. As the Cholesky of a matrix is _unique_, I cannot see how `B == A` can be true without `cholesky1 == C`. So I think I must have misinterpreted that last part - could you elaborate slightly, perhaps?

Many thanks!
Martijn

**Comment by jor-** [comment]
Dear Martijn,

thank you for pointing out, that https://pythonhosted.org/scikit-sparse/cholmod.html is outdated. We should updated this one. @anntzer: Do you now how to update this?

The reason why `ordering_method="natural"` is not the default is that the computation with the natural ordering usually needs much more memory than with the other ordering methods. But you are right, we should extend the documentation regarding this.

In my comment, `C` is not the Cholesky factor of `A`. It is just some matrix so that `C @ C.T` is equal to `A`.

Best regards,
Joscha

**Comment by njsmith** [comment]
> thank you for pointing out, that https://pythonhosted.org/scikit-sparse/cholmod.html is outdated.

It can't be updated; the whole platform is being phased out and no new uploads are allowed. The only thing you can do is delete the docs from pythonhosted.org, which is probably a good idea to do.

To do this, you go to https://pypi.org/manage/project/scikit-sparse/releases/, click "Documentation" on the left, and then follow the instructions.

I just did it for the old pythonhosted.org/scikits.sparse docs, but I don't have permissions for pythonhosted.org/scikit-sparse.

**Comment by jor-** [comment]
> It can't be updated; the whole platform is being phased out and no new uploads are allowed. The only thing you can do is delete the docs from pythonhosted.org, which is probably a good idea to do.

Thank you for the clarification.

> I just did it for the old pythonhosted.org/scikits.sparse docs, but I don't have permissions for pythonhosted.org/scikit-sparse.

@anntzer: You should have the necessary permissions.

**Comment by anntzer** [comment]
Done.

**Comment by jor-** [comment]
> Done.

Thank you.

**Comment by MartijnOei** [comment]
Thank you for your responses! It's highly appreciated. I have - if I may - one last question on this.

> The reason why ordering_method="natural" is not the default is that the computation with the natural ordering usually needs much more memory than with the other ordering methods. But you are right, we should extend the documentation regarding this.

> In my comment, C is not the Cholesky factor of A. It is just some matrix so that C @ C.T is equal to A.

Yes, I understand that `ordering_method="natural"` is sub-optimal in terms of performance (both in memory and arithmetic complexity, I guess). On second thought I think that users of this package are already looking for performance boosts, so I can appreciate why you want a fancy `ordering_method` other than `"natural"` to be the default.
My question: From theory I know that when I multiply the 'naive' (sparse) Cholesky `cholesky1`, such as in
```python
factor       = cholmod.cholesky(A_CSC, ordering_method = "natural")
cholesky1    = factor.L()
```
with a vector of uncorrelated standard normal random variables, then the resulting vector has correlations according to correlation / covariance matrix `A_CSC`.

However, I'm interested in leveraging your internal optimisations (so I would like to _not_ use `ordering_method="natural"`, preferably), while still being able to generate correlated Gaussian random variables.
Could I obtain my `cholesky1` without using `ordering_method="natural"`? Or could I work with the `factor.L()` obtained by running `cholmod.cholesky` with another `ordering_method`? Some numerical experimentation shows that samples generated with the `C` of
```python
factorSmart  = cholmod.cholesky(A_CSC)
p            = factorSmart.P()
p_inverse    = numpy.empty_like(p)
p_inverse[p] = numpy.arange(len(p))
C            = factorSmart.L().toarray()[p_inverse[:, numpy.newaxis], p_inverse[numpy.newaxis, :]]
```
also look pretty Gaussian. Am I correct? (I can't reason well about this myself, as I'm not exactly sure what the other ordering methods do.)

**Comment by jor-** [comment]
If you multiply `C` with a vector of uncorrelated standard normal random variables, the resulting vector has a covariance matrix of `A_CSC` as well.

But you could also do it with less computational effort like:
```
factor = cholmod.cholesky(A_CSC)
L = factor.L()
z = np.random.rand(L.shape[0])
p = factor.P()
p_inverse = np.empty_like(p)
p_inverse[p] = np.arange(len(p))
y = (L @ z)[p_inverse]
```
Then `y` is generated as well by a random vector with covariance matrix of `A_CSC`.

**Comment by MartijnOei** [comment]
Very clear; thank you again!
