### ISSUE TITLE
Support Apple silicon?

### ISSUE THREAD

**Issue by QYQSDTC** [scikit-sparse/scikit-sparse#73]
I met errors below when installing on Apple's M1 chip MBP
---------------------------------
```bash
pip install -U scikit-sparse
Collecting scikit-sparse
  Downloading scikit-sparse-0.4.6.tar.gz (209 kB)
     |████████████████████████████████| 209 kB 310 kB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /private/var/folders/8j/473p19jj4vd201q3fw1x8flw0000gn/T/pip-standalone-pip-owb0loi4/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/8j/473p19jj4vd201q3fw1x8flw0000gn/T/pip-build-env-zg2p25su/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel 'Cython>=0.22' 'numpy==1.13.3; python_version=="3.6"' 'numpy==1.14.5; python_version=="3.7"' 'numpy==1.17.3; python_version=="3.8"' 'numpy==1.19.3; python_version=="3.9"'
       cwd: None
  Complete output (21 lines):
  Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9"' don't match your environment
  Collecting setuptools>=40.8.0
    Downloading setuptools-59.4.0-py3-none-any.whl (952 kB)
  Collecting wheel
    Downloading wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting Cython>=0.22
    Downloading Cython-0.29.24-py2.py3-none-any.whl (979 kB)
  Collecting numpy==1.17.3
    Downloading numpy-1.17.3.zip (6.4 MB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Building wheels for collected packages: numpy
    Building wheel for numpy (setup.py): started
    Building wheel for numpy (setup.py): finished with status 'done'
    Created wheel for numpy: filename=numpy-1.17.3-cp38-cp38-macosx_12_0_arm64.whl size=3673759 sha256=17d72064155a29695dcf36dc01dd65ea9f662a1981df5caea727b859bb1da01b
    Stored in directory: /Users/qyq/Library/Caches/pip/wheels/aa/67/93/1a3eb3ad40a08a0cc44ce3da7bfcad685c04afba45b7e72589
  Successfully built numpy
  Installing collected packages: wheel, setuptools, numpy, Cython
  ERROR: Cannot set --home and --prefix together
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ca/91/94db555d5c7b0f75ecdf14802613409b9977aa8a92d0925863051e59c17b/scikit-sparse-0.4.6.tar.gz#sha256=f2de653920c2adf666de5c8a28abaa9f2218a1001d2d96e403a1f553938561c3 (from https://pypi.org/simple/scikit-sparse/) (requires-python:>=3.6, <3.10). Command errored out with exit status 1: /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /private/var/folders/8j/473p19jj4vd201q3fw1x8flw0000gn/T/pip-standalone-pip-owb0loi4/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/8j/473p19jj4vd201q3fw1x8flw0000gn/T/pip-build-env-zg2p25su/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel 'Cython>=0.22' 'numpy==1.13.3; python_version=="3.6"' 'numpy==1.14.5; python_version=="3.7"' 'numpy==1.17.3; python_version=="3.8"' 'numpy==1.19.3; python_version=="3.9"' Check the logs for full command output.
```
SuiteSpase is successfully installed using Homebrew.

**Comment by AaronDJohnson** [comment]
I was able to get this to install properly on my M1 Mac (with Python version 3.9.10) by installing `suitesparse` via `brew install suitesparse` and changing the `numpy` version in `pyproject.toml` to `1.22.2`. Also, it appears that the default directory for the homebrew installation has changed to /opt/homebrew/Cellar/suite-sparse/[version]. So adding /opt/homebrew/Cellar/suite-sparse/[version]/include to the include path and /opt/homebrew/Cellar/suite-sparse/[version]/lib to the library path in the `setup.py` file was also necessary.

**Comment by QYQSDTC** [comment]
Thanks @AaronDJohnson, I fixed this using another package manager MacPorts.

BTW, I see you are working on PTA? We are on the same boat 😂 , your analysis repos on NANOGrav 12.5 yrs data might help me a lot. Do you successfully install the bunch of psr software on Mac, i.e. Tempo2 etc.

**Comment by AaronDJohnson** [comment]
@QYQSDTC Nice! If you have any issues with the tutorials (or would like to talk about the software at all), my email is there at the top of the README in that repo. The tutorials are still in the process of being updated just a little bit due to some recent changes in the NANOGrav software. Unfortunately, TEMPO2 doesn't appear to be working natively on M1 Mac at the moment. PINT, the NANOGrav equivalent of this _does_ work, but not for timing. PINT makes extensive use of extended precision that isn't available on M1 Macs natively. However, everything (TEMPO2 and PINT with extended precision) will work if you go through Rosetta. Instructions on how to do this can be found here: [https://conda-forge.org/docs/user/tipsandtricks.html#installing-apple-intel-packages-on-apple-silicon](https://conda-forge.org/docs/user/tipsandtricks.html#installing-apple-intel-packages-on-apple-silicon). I do hope to get at least PINT working natively in the near future though.

**Comment by QYQSDTC** [comment]
@AaronDJohnson Thanks for the advice, but I failed to install tempo2 on my old 2016 MBP either which is intel based 😂 , maybe I was trying to install manually and didn't go through conda, since I am actively using MacPorts and Homebrew as my package manager. I have no problem with ENTERPRISE and PINT both are run smoothly on my new M1 Mac, but I am interested in how to install tempo2, psrchive, and those kinds of old psr softwares on M1, no matter through conda or Rosseta, the only way I can use them now is through Docker on my old MBP which is kind of slow. So, could u please give me a basic guide on how to install tempo2, psrchive, etc. on M1 through conda? Thanks!

**Comment by AaronDJohnson** [comment]
@QYQSDTC I'm not sure about psrchive, but you can set up a Rosetta environment using this: https://conda-forge.org/docs/user/tipsandtricks.html#installing-apple-intel-packages-on-apple-silicon. After setting up such an environment, `conda install -c conda-forge enterprise_extensions` will install all of the NANOGrav detection working group software. For the newest version of TEMPO2, you will probably need a separate installation or environment, but you should be able to use `conda install -c conda-forge tempo2`. For a faster response to further questions, you can email me directly at aaron.johnson (at) nanograv.org. I may not have all of the answers, but I can put you in touch with someone who does!

**Comment by QYQSDTC** [comment]
@AaronDJohnson Ok, thanks a lot! Let me give it a shot.

**Comment by Wenxuan-Zhou** [comment]
I was able install on M1 by simply changing the numpy version in pyproject.toml from 1.19.3 to 1.23.1

**Comment by cshang-rbx** [comment]
>changing the numpy version in pyproject.toml to 1.22.2 (I'm actually using 1.25.2)

works for me as well, thanks @AaronDJohnson !
