### ISSUE TITLE
Pip installation fails during cython compilation

### ISSUE THREAD

**Issue by mo-kli** [scikit-sparse/scikit-sparse#91]
Compilation during installation via pip results in the following error. Most likely due to a [new release ](https://github.com/cython/cython/releases/tag/3.0.0) of Cython yesterday.

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              cholmod_c_start(&self._common)
              assert (_use_long == 0 and self._common.itype == CHOLMOD_INT) \
                  or (_use_long == 1 and self._common.itype == CHOLMOD_LONG)
              self._common.print = 0
              self._common.error_handler = (
                  <void (*)(int, const char *, int, const char *)>_error_handler)
                  ^
      ------------------------------------------------------------
      
      sksparse/cholmod.pyx:435:12: Cannot assign type 'void (*)(int, const char *, int, const char *) except *' to 'void (*)(int, const char *, int, const char *) noexcept'
      Compiling sksparse/cholmod.pyx because it changed
```

**Comment by luisenp** [comment]
Our [project](https://github.com/facebookresearch/theseus) is affected by this error as well, which is currently breaking our CI.

**Comment by luisenp** [comment]
In reference to [this](https://github.com/scikit-sparse/scikit-sparse/pull/92#issuecomment-1644274744), is there a reason why 0.4.9 fix wasn't uploaded to `pypi`?

**Comment by AaronDJohnson** [comment]
> In reference to [this](https://github.com/scikit-sparse/scikit-sparse/pull/92#issuecomment-1644274744), is there a reason why 0.4.9 fix wasn't uploaded to `pypi`?

The build failed, because I forgot to limit the build version number on cython. I have another PR open to fix it. I'll rerelease 0.4.9 after this, and then I'll try to update the code to support cython >= 3.0.

**Comment by AaronDJohnson** [comment]
I think this issue has been resolved. @mo-kli can you check that things are working for you now?

**Comment by luisenp** [comment]
Confirm that it works now, thanks for the quick fix!
